export const ACTION_SIGN_IN = "SIGN_IN";
export const ACTION_GET_USER = "GET_USER";
export const ACTION_UPDATE_USER = "UPDATE_USER";
export const ACTION_ADD_HOSPITAL = "ADD_HOSPITAL";

export const ACTION_ADD_MODELS = "ADD_MODELS";
export const ACTION_GET_MODELS = "GET_MODELS";
export const ACTION_CLEAR_MODELS = "CLEAR_MODELS";

export const ACTION_ADD_MODELS_STORE = "ADD_MODELS_STORE";
export const ACTION_GET_MODELS_STORE = "GET_MODELS_STORE";
export const ACTION_CLEAR_MODELS_STORE = "CLEAR_MODELS_STORE";

export const ACTION_CLEAR_REPORTS = "CLEAR_REPORTS";
export const ACTION_ADD_REPORTS = "ADD_REPORTS";
export const ACTION_GET_REPORTS = "GET_REPORTS";